# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mantra - An Application Architecture for Meteor
email: hello@mantrajs.org
description: > # this means to ignore newlines until "baseurl:"
  Mantra is a specification for Meteor applications using the current
  and future proof coding patterns to keep you and your team productive
  and on track.
baseurl: "/mantrajs-website" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: mantrajs
github_username:  mantrajs

# Build settings
markdown: kramdown
